<?php echo $this->doctype(); ?>
<html xmlns="http://www.w3.org/1999/xhtml"  xmlns:fb="http://ogp.me/ns/fb#">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8"/>
<title>AireToChina</title>
<meta name="keywords" content="">
<meta name="description" content="">
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-12141277-3']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<?php
    echo $this->headLink();
    echo $this->headStyle();
    echo $this->headScript();
?>
    
    <script> var baseUrl = '<?php echo $this->baseUrl();?>';</script>
</head>
<body>
        <?php echo $this->render('header.phtml'); ?>
        <?php echo $this->layout()->content; ?>
        <?php echo $this->render('footer.phtml'); ?>
</body>
</html>