<table width="231" height="570" border="0" cellpadding="0" cellspacing="0" class="border1">
              <tr>
                <td width="306"><span class="title">Find Your Flight</span></td>
              </tr>
              <tr>
                <td width="306"><a href="javascript:void(0);" onclick="getPeopleonSameFlight();"><span class="fb">See Who's sitting where</span></a></td>
              </tr>
               <tr>
                <td width="306"><span class="fb">Assign your seat</span></td>
              </tr>
               <tr>
                <td width="306"><span class="fb">Tag your friends</span></td>
              </tr>
               <tr>
                <td width="306"><span class="gray">Cabin Composition</span></td>
              </tr>
              <tr>
                <td width="306"><span class="gray">Show Flight Mood On map</span></td>
              </tr>
              <tr>
                <td width="306"><span class="gray">Mood Around and Zoom In/Out</span></td>
              </tr>
              <tr>
                <td width="306"><span class="gray">Learn More About Seat Features</span></td>
              </tr>
              <tr>
                <td width="306"><span class="gray">Hotel/Taxi/Insurance</span></td>
              </tr>
              <tr>
                <td width="306"><span class="gray">Review Seat and Check Out </span></td>
              </tr>
          </table>
<script type="text/javascript">
ddaccordion.init({
	headerclass: "submenuheader", //Shared CSS class name of headers group
	contentclass: "submenu", //Shared CSS class name of contents group
	revealtype: "click", //Reveal content when user clicks or onmouseover the header? Valid value: "click", "clickgo", or "mouseover"
	mouseoverdelay: 200, //if revealtype="mouseover", set delay in milliseconds before header expands onMouseover
	collapseprev: true, //Collapse previous content (so only one open at any time)? true/false 
	defaultexpanded: [], //index of content(s) open by default [index1, index2, etc] [] denotes no content
	onemustopen: false, //Specify whether at least one header should be open always (so never all headers closed)
	animatedefault: false, //Should contents open by default be animated into view?
	persiststate: true, //persist state of opened contents within browser session?
	toggleclass: ["", ""], //Two CSS classes to be applied to the header when it's collapsed and expanded, respectively ["class1", "class2"]
	togglehtml: ["suffix", "<img src='<?php echo $this->baseUrl(); ?>/public/images/plus.gif' class='statusicon' />", "<img src='<?php echo $this->baseUrl(); ?>/public/images/minus.gif' class='statusicon' />"], //Additional HTML added to the header when it's collapsed and expanded, respectively  ["position", "html1", "html2"] (see docs)
	animatespeed: "fast", //speed of animation: integer in milliseconds (ie: 200), or keywords "fast", "normal", or "slow"
	oninit:function(headers, expandedindices){ //custom code to run when headers have initalized
		//do nothing
	},
	onopenclose:function(header, index, state, isuseractivated){ //custom code to run whenever a header is opened or closed
		//do nothing
	}
});
</script>
