<h1 id="an-error-occurred">An error occurred</h1>
<h3 id=""><?php echo $this->message ?></h3> 

<?php if ('development' == $this->env /*|| 'production' == $this->env*/): ?> 

    <h4 id="exception-information">Exception information:</h4>
    <p>
      <strong>Message:</strong> <?php echo $this->exception->getMessage(); ?>
    </p> 

    <h4 id="stack-trace">Stack trace:</h4>
    <pre><?php echo $this->exception->getTraceAsString() ?></pre> 

    <h4 id="request-parameters">Request Parameters:</h4>
    <?php var_dump($this->request->getParams()); ?>

<?php 
endif;
