<table width="100%">
    <tr>
        <td align="center">Down Town</td><td align="right"><img src="<?php echo $this->baseUrl().'/public/images/taxi.png'; ?>"></?php></td>
    </tr>
    <tr>
        <td align="center">Mid Town</td><td align="right"><img src="<?php echo $this->baseUrl().'/public/images/taxi.png'; ?>"></td>
    </tr>
    <tr>
        <td align="center">Up Town</td><td align="right"><img src="<?php echo $this->baseUrl().'/public/images/taxi.png'; ?>"></td>
    </tr>
</table>